/*
 * L298N.h
 *
 *  Created on: Dec 21, 2021
 *      Author: pawel
 */

#ifndef INC_L298N_H_
#define INC_L298N_H_

#define DIR1_GPIO_PORT	GPIOB
#define DIR2_GPIO_PORT	GPIOB
#define DIR1_PIN		GPIO_PIN_10
#define DIR2_PIN		GPIO_PIN_11

#define LN298N_MOTOR_OFF()	HAL_GPIO_WritePin(DIR1_GPIO_PORT, DIR1_PIN, GPIO_PIN_RESET);HAL_GPIO_WritePin(DIR2_GPIO_PORT, DIR2_PIN, GPIO_PIN_RESET)
#define LN298N_MOTOR_FORWARD()	HAL_GPIO_WritePin(DIR1_GPIO_PORT, DIR1_PIN, GPIO_PIN_SET);HAL_GPIO_WritePin(DIR2_GPIO_PORT, DIR2_PIN, GPIO_PIN_RESET)
#define LN298N_MOTOR_BACKWARD()	HAL_GPIO_WritePin(DIR1_GPIO_PORT, DIR1_PIN, GPIO_PIN_RESET);HAL_GPIO_WritePin(DIR2_GPIO_PORT, DIR2_PIN, GPIO_PIN_SET)


#endif /* INC_L298N_H_ */
